//
// Created by giacomo on 1/19/26.
//

#include <iostream>
#include <string>
#include <filesystem>
#include <fstream>
namespace fs = std::filesystem;

#include "opencv2/core.hpp"
#include <opencv2/core/mat.hpp>
#include <opencv2/imgcodecs.hpp>
#include <cuda_runtime.h>
#include <cuda_runtime_api.h>
#include "src/kernel_functions.h"
#include "src/cuda_kernel.cuh"
#include <omp.h>

//Generated by Gemini pro to handle CUDA errors
#define CUDA_CHECK(call) \
do { \
    cudaError_t err = call; \
    if (err != cudaSuccess) { \
        fprintf(stderr, "CUDA error at %s:%d code=%d(%s) \n", \
        __FILE__, __LINE__, err, cudaGetErrorString(err)); \
        exit(EXIT_FAILURE); \
    } \
} while (0)


#define MAX_W 1024
#define MAX_H 1024
#define K 7
#define C 3

int main() {
    auto start_e2e = std::chrono::high_resolution_clock::now();

    float kernel[K*K];
    generateKernel(kernel, Gaussian7);

    loadKernel(kernel, K);

    unsigned char * deviceInput;
    unsigned char * deviceOutput;

    cudaMalloc(&deviceInput, MAX_W*MAX_H*sizeof(unsigned char)*C);
    cudaMalloc(&deviceOutput, MAX_W*MAX_H*sizeof(unsigned char)*C);

    //we choose blocks 32x4. So, to cover all the images 150*150 we need a grid 5x38
    //for 1024x1024 we choose blocks 32x4, so a grid 32x256
    dim3 dimGrid(5,38);
    dim3 dimBlock(32,4);

    std::string path = "../dataset_150x150/seg_pred/seg_pred";
    int count = 0;

    double total_k = 0;

    std::vector<std::filesystem::path> imgList;
    for (const auto & entry : fs::directory_iterator(path)) {
        imgList.push_back(entry.path());
    }



    int N = 4;
    omp_set_num_threads(N);

#pragma omp parallel
    {
        cudaStream_t st;
        int id = omp_get_thread_num();

        unsigned char* inputPinned;
        unsigned char* outputPinned;
        cudaMallocHost(&inputPinned, MAX_W*MAX_H*sizeof(unsigned char)*C);
        cudaMallocHost(&outputPinned, MAX_W*MAX_H*sizeof(unsigned char)*C);

        for (int i = id; i < imgList.size(); i += N) {

            cv::Mat inputImg = cv::imread(imgList[i], cv::IMREAD_UNCHANGED);

            if (inputImg.empty()) {
                continue;
            }

            cv::Size size = inputImg.size();

            //Access raw bytes of the image
            auto inputPtr = inputImg.ptr();

            memcpy(inputPinned, inputPtr, sizeof(unsigned char)*size.width*size.height*C);

            cv::Mat outputImg = cv::Mat::zeros(inputImg.size(), inputImg.type());

            auto outputPtr = outputImg.ptr();

            auto start_k = std::chrono::high_resolution_clock::now();

            cudaMemcpyAsync(deviceInput, inputPinned, sizeof(unsigned char)*size.height*size.width*inputImg.channels(), cudaMemcpyKind::cudaMemcpyHostToDevice, st);

            int dimTile = (dimBlock.x + (K-1))*(dimBlock.y + (K-1))*C;

            // the third parameter in <<< >>> is ignored if the shared memory is not allocated
            applyCudaKernel <<<dimGrid, dimBlock, dimTile, st>>> (deviceInput, deviceOutput, K, size.width, size.height, inputImg.channels());
            cudaMemcpyAsync(outputPinned, deviceOutput, sizeof(unsigned char)*size.height*size.width*inputImg.channels(), cudaMemcpyKind::cudaMemcpyDeviceToHost, st);
            cudaStreamSynchronize(st);
            auto end_k = std::chrono::high_resolution_clock::now();


            auto temp = std::chrono::duration_cast<std::chrono::duration<double>>(end_k - start_k).count();
#pragma omp atomic
            total_k += temp;

            memcpy(outputPtr, outputPinned, sizeof(unsigned char)*size.width*size.height*C);

            std::string outputPath = "../cuda_output_150_7.3k/" + imgList[i].filename().string();
            cv::imwrite(outputPath, outputImg);
        }
        cudaFree(deviceInput);
        cudaFree(deviceOutput);
        cudaFree(inputPinned);
        cudaFree(outputPinned);
    }
    auto end_e2e = std::chrono::high_resolution_clock::now();
    auto time_e2e = std::chrono::duration_cast<std::chrono::duration<double>>(end_e2e - start_e2e).count();

    std::cout << "Time Taken End to End:" << time_e2e << "s" << std::endl;
    std::cout << "Time Taken to apply kernel:" << total_k/imgList.size() << "s" << std::endl;
    std::cout << "Elements Elaborated:" << imgList.size() << std::endl;
}