//
// Created by giacomo on 1/19/26.
//

#include <iostream>
#include <string>
#include <filesystem>
#include <fstream>
namespace fs = std::filesystem;

#include "opencv2/core.hpp"
#include <opencv2/core/mat.hpp>
#include <opencv2/imgcodecs.hpp>
#include "src/parallel_kernel.h"
#include <omp.h>

//Generated by Gemini pro to handle CUDA errors
#define CUDA_CHECK(call) \
do { \
    cudaError_t err = call; \
    if (err != cudaSuccess) { \
        fprintf(stderr, "CUDA error at %s:%d code=%d(%s) \n", \
        __FILE__, __LINE__, err, cudaGetErrorString(err)); \
        exit(EXIT_FAILURE); \
    } \
} while (0)

#define MAX_K 7
#define MAX_W 150
#define MAX_H 150

int main() {



    auto start_e2e = std::chrono::high_resolution_clock::now();

    float kernel[9];
    generateKernel(kernel, Gaussian);

    __constant__ float cuda_kernel[MAX_K*MAX_K];

    cudaMemcpy(cuda_kernel, kernel, sizeof(float)*9, cudaMemcpyKind::cudaMemcpyHostToDevice);

    unsigned char * deviceInput;
    unsigned char * deviceOutput;

    cudaMalloc(&deviceInput, MAX_W*MAX_H*sizeof(unsigned char));
    cudaMalloc(&deviceOutput, MAX_W*MAX_H*sizeof(unsigned char));

    std::string path = "../dataset/seg_pred/seg_pred";
    int count = 0;

    double total_k = 0;
    for (const auto & entry : fs::directory_iterator(path)) {
        cv::Mat inputImg = cv::imread(entry.path(), cv::IMREAD_UNCHANGED);
        cv::Mat outputImg = cv::Mat::zeros(inputImg.size(), inputImg.type());

        if (inputImg.empty()) {
            continue;
        }

        cv::Size size = inputImg.size();

        //Access raw bytes of the image
        auto inputPtr = inputImg.ptr();
        auto outputPtr = outputImg.ptr();

        auto start_k = std::chrono::high_resolution_clock::now();
        // TO DO: insert ApplyKernelCuda or similar
        auto end_k = std::chrono::high_resolution_clock::now();
        total_k += std::chrono::duration_cast<std::chrono::duration<double>>(end_k - start_k).count();
        count++;
    }

    cudaFree(deviceInput);
    cudaFree(deviceOutput);

    auto end_e2e = std::chrono::high_resolution_clock::now();
    auto time_e2e = std::chrono::duration_cast<std::chrono::duration<double>>(end_e2e - start_e2e).count();


    std::cout << "Time Taken End to End:" << time_e2e << "s" << std::endl;
    std::cout << "Time Taken to apply kernel:" << total_k/count << "s" << std::endl;
    std::cout << "Elements Elaborated:" << count << std::endl;

}
