//
// Created by giacomo on 1/26/26.
//


#include <iostream>
#include <string>
#include <filesystem>
#include <fstream>

namespace fs = std::filesystem;

#include "opencv2/core.hpp"
#include <opencv2/core/mat.hpp>
#include <opencv2/imgcodecs.hpp>
#include <cuda_runtime.h>
#include <cuda_runtime_api.h>
#include "src/kernel_functions.h"
#include "src/cuda_kernel.cuh"
#include <omp.h>

//Generated by Gemini pro to handle CUDA errors
#define CUDA_CHECK(call) \
do { \
    cudaError_t err = call; \
    if (err != cudaSuccess) { \
        fprintf(stderr, "CUDA error at %s:%d code=%d(%s) \n", \
        __FILE__, __LINE__, err, cudaGetErrorString(err)); \
        exit(EXIT_FAILURE); \
    } \
} while (0)



#define BATCH_SIZE 64

int main(int argc, char* argv[]) {
    Config cfg;

    cfg.parse(argc, argv);

    omp_set_num_threads(cfg.threads);

    auto start_e2e = std::chrono::high_resolution_clock::now();

    float kernel[MAX_K*MAX_K];
    generateKernel(kernel, cfg.kernelType);

    loadKernel(kernel, cfg.K);

    //we choose blocks 32x4. So, to cover all the images 150*150 we need a grid 5x38
    //for 1024x1024 we choose blocks 32x4, so a grid 32x256

    dim3 dimBlock(32,4);

    std::string path = cfg.datasetPath;

    double total_k = 0;

    std::vector<std::filesystem::path> imgList;
    for (const auto & entry : fs::directory_iterator(path)) {
        imgList.push_back(entry.path());
    }

    cv::Size size;
    int imgType;
    int channels;

    unsigned char* batchPtr;
    unsigned char* deviceInput;
    unsigned char* deviceOutput;

    CUDA_CHECK(cudaMallocHost(&batchPtr, sizeof(unsigned char)*MAX_W*MAX_H*MAX_C*BATCH_SIZE));
    CUDA_CHECK(cudaMalloc(&deviceInput, sizeof(unsigned char)*MAX_W*MAX_H*MAX_C*BATCH_SIZE));
    CUDA_CHECK(cudaMalloc(&deviceOutput, sizeof(unsigned char)*MAX_W*MAX_H*MAX_C*BATCH_SIZE));

    for (int i=0; i <= imgList.size()/BATCH_SIZE; i++) {
        int currentBatchSize=0;

        for (int j=0; j<BATCH_SIZE; j++) {

            int generalIndex= i*BATCH_SIZE + j;

            if (generalIndex >= imgList.size()) {
                break ;
            }
            currentBatchSize++;
            cv::Mat inputImg = cv::imread(imgList[generalIndex], cv::IMREAD_UNCHANGED);
            size = inputImg.size();
            imgType = inputImg.type();
            channels = inputImg.channels();
            memcpy(batchPtr + j*sizeof(unsigned char)*MAX_W*MAX_H*MAX_C, inputImg.ptr(), sizeof(unsigned char)*size.area()*channels);
        }

        dim3 dimGrid((size.width/dimBlock.x)+1,(size.height/dimBlock.y)+1, currentBatchSize);
        cudaMemcpy(deviceInput, batchPtr, sizeof(unsigned char)*MAX_W*MAX_H*MAX_C*BATCH_SIZE, cudaMemcpyHostToDevice);

        applyCudaKernel <<<dimGrid, dimBlock>>> (deviceInput, deviceOutput, cfg.K, size.width, size.height, channels);
        cudaMemcpy(batchPtr, deviceOutput, sizeof(unsigned char)*MAX_W*MAX_H*MAX_C*BATCH_SIZE, cudaMemcpyDeviceToHost);

        for (int j=0; j<currentBatchSize; j++) {

            int generalIndex= i*BATCH_SIZE + j;

            if (generalIndex >= imgList.size()) {
                break ;
            }

            cv::Mat outputImg =  cv::Mat::zeros(size, imgType);
            memcpy(outputImg.ptr(), batchPtr + j*sizeof(unsigned char)*MAX_W*MAX_H*MAX_C, sizeof(unsigned char)*size.area()*channels);

            std::string outputPath = "../cuda_output_" + std::to_string(size.width) + "_" + "k=" + std::to_string(cfg.K) + "/" + imgList[generalIndex].filename().string();
            cv::imwrite(outputPath, outputImg);

        }

    }
        CUDA_CHECK(cudaFree(deviceInput));
        CUDA_CHECK(cudaFree(deviceOutput));
        CUDA_CHECK(cudaFreeHost(batchPtr));

    auto end_e2e = std::chrono::high_resolution_clock::now();
    auto time_e2e = std::chrono::duration_cast<std::chrono::duration<double>>(end_e2e - start_e2e).count();

    std::cout << "Time Taken End to End:" << time_e2e << "s" << std::endl;
    std::cout << "Elements Elaborated:" << imgList.size() << std::endl;

    append_csv(cfg, size.width, imgList.size(), 0, time_e2e, cfg.outputPath);
}